name: CI

on:
  push:
    branches: ["main"]
    paths-ignore: ["*.md", "docs", "deploy", "config", ".github", "scripts"]

  pull_request:
    branches: ["main"]
    paths-ignore: ["*.md", "docs", "deploy", "config", ".github", "scripts"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.commits[0].message, '[skip ci]') == false &&
      contains(github.event.commits[0].message, '[ci skip]') == false
    steps:
      - uses: actions/checkout@v3

        # https://github.com/actions/setup-go/issues/326
        # https://github.com/testcontainers/testcontainers-go/issues/1359
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
        id: go

      - name: Cache go modules
        id: cache
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

        # https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies
        # https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns
      - name: Build
        run: make build

      - name: Tests
        run: go test -count=1 -p=1 -parallel=1 ./...